apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80             # Service port (what clients use)
      targetPort: 80       # Container port (inside pod)
      nodePort: 31443 
